name: Testproject CCDCD

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/5 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Testproject Job
        run: docker-compose -f binh.yml up --abort-on-container-exit
